spring.application.name=teststream
spring.config.import=optional:file:.env[.properties]
server.tomcat.accesslog.enabled=true

server.forward-headers-strategy=framework
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.servlet.session.timeout=30m

spring.datasource.url=${DB_URL:jdbc:h2:mem:teststream_local;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console