spring.application.name=teststream
spring.config.import=optional:file:.env[.properties]
server.tomcat.accesslog.enabled=true

server.forward-headers-strategy=framework
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.servlet.session.timeout=30m
spring.session.jdbc.initialize-schema=always

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
